### ISSUE TITLE
надо срочно размещать лого спонсоров

### ISSUE THREAD

**Issue by pcshiver** [VolgaCTF/volgactf-site#6]
ГИС И вебмани

**Comment by aspyatkin** [comment]
Who has the necessary logos?

**Comment by pcshiver** [comment]
у Волкова в почте они

2015-08-26 11:20 GMT+04:00 Alexander Pyatkin <notifications@github.com>:

> Who has the necessary logos?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VolgaCTF/volgactf-site/issues/6#issuecomment-134874155>
> .
>



-- 
С уважением, Павел Шиверов.

**Comment by pcshiver** [comment]
теперь и у тебя в почте)

2015-08-26 11:20 GMT+04:00 Павел Шиверов <pcshiverov@gmail.com>:

> у Волкова в почте они
>
> 2015-08-26 11:20 GMT+04:00 Alexander Pyatkin <notifications@github.com>:
>
>> Who has the necessary logos?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/VolgaCTF/volgactf-site/issues/6#issuecomment-134874155>
>> .
>>
>
>
>
> --
> С уважением, Павел Шиверов.
>



-- 
С уважением, Павел Шиверов.
